"""
# https://leetcode.com/problems/find-the-difference/

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Input: s = "", t = "y"
Output: "y"
"""

from typing import Counter
from markupsafe import re


s = "abcd"
t = "abcde"

def findTheDifference(s, t):
    # s_cnt, t_cnt = Counter(s), Counter(t)
    # for letter in t_cnt:
    #     if not s_cnt[letter] == t_cnt[letter]:
    #         return letter
    for i in t:
        if s.count(i) != t.count(i):
            return i 

print(
    findTheDifference(s, t)
)